Resources:
  # s3 bucket to store downloadable quizzes
  DownloadBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      BucketName: 'instant-trivia-download'
      PublicAccessBlockConfiguration: 
          BlockPublicAcls: True
          BlockPublicPolicy: True
          IgnorePublicAcls: True
          RestrictPublicBuckets: True
      VersioningConfiguration: 
        Status: Enabled
    DeletionPolicy: Delete

  # download bucket policy
  DownloadBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref DownloadBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:AbortMultipartUpload'
              - 's3:GetObject'
              - 's3:GetObjectVersion'
              - 's3:PutObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref DownloadBucket
                - /*
            # TODO needs to be dynamic
            Principal: 'arn:aws:iam::216835676480:role/service-role/getQuestions-role-1g8vur7n'

  # TODO: lifecycle rule for download bucket

  # s3 bucket for uploading questions
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      BucketName: 'instant-trivia-upload'
      PublicAccessBlockConfiguration: 
          BlockPublicAcls: True
          BlockPublicPolicy: True
          IgnorePublicAcls: True
          RestrictPublicBuckets: True
      VersioningConfiguration: 
        Status: Enabled
    DeletionPolicy: Delete

  # upload bucket policy
  UploadBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref UploadBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref UploadBucket
                - /*
            # TODO needs to be dynamic
            Principal: 'arn:aws:iam::216835676480:role/service-role/loadData-role-3rqtsv62'
